#! /bin/env bash

# functions for data pipe port tools
# created on 2018-11-12, by wangzheny
function is_file {
	if [ ! -f "$1" ] ; then
		echo "文件:$1 不存在或文件名错误"
		exit 2
	fi
}

function is_dir {
	if [ ! -d "$1" ] ; then
		echo "目录: $1 不存在。"
		exit 2
	fi
}

# 规范[表清单需求文件]的内容
# 删除空行、dos符号、全部转换成大写
# 参数输入：[表清单需求文件]的名字
function handleFormat {
	is_file "$1"
	sed -i 's/^M//' $1
	sed -i '/^$/d' $1
	sed -i 's/[a-z]/\u&/g' $1
}

# 判断是否已经安装了sshpass工具，如果没有安装则自动安装
function isInstallTool(){
which $1>/dev/null 2>&1
if [ "$?" -eq 1 ]; then 
	echo "服务器没有安装${1}或当前用户没有执行${1}的权限。" 
	exit
fi
}

function log {
    echo -e "\n"
    printf -- "$@"
    echo -e "\n"
}

# $1: password string
# $2: in or out
function encryptPWD() {
   if [ "$2" == "in" ]; then
      ori_pass=$1
      enc_pass=$(echo "$1" | base64 -i)   
      echo ${enc_pass}
   fi

   if [ "$2" == "out" ]; then
      ori_pass=$1
      enc_pass=$(echo "$1" | base64 -d)   
      echo ${enc_pass}
   fi
}
